#Use this file to add images for OS's
OSDict = {"windows 10":"https://imgur.com/kxO5E9i.png",
          "windows 11":"https://imgur.com/o8kY5or.png",
          "windows 8":"https://imgur.com/FvYjSTf.png",
          "windows 7":"https://imgur.com/L77FPCt.png",
          "windows vista":"https://imgur.com/L77FPCt.png",
          "windows xp":"https://imgur.com/L77FPCt.png",
          "windows server":"https://i.imgur.com/nVHdZcn.png",
          "windows 95":"https://i.imgur.com/RY7LFUn.png",
          "windows 98":"https://i.imgur.com/RY7LFUn.png",
          "windows nt":"https://i.imgur.com/RY7LFUn.png",
          "windows 2000":"https://i.imgur.com/RY7LFUn.png",
          "windows":"https://imgur.com/L77FPCt.png",
          "dos":"https://i.imgur.com/B3YCZVZ.png",
          "kali":"https://imgur.com/R1WBgCS.png",
          "ubuntu":"https://imgur.com/Woznh88.png",
          "centos":"https://i.imgur.com/Pt1nSt2.png",
          "red hat":"https://i.imgur.com/p48NNtO.png",
          "rhel":"https://i.imgur.com/p48NNtO.png",
          "opnsense":"https://pbs.twimg.com/profile_images/550182897550757888/7Ro0MJbW_400x400.png",
          "pfsense":"https://www.itandgeneral.com/wp-content/uploads/2023/11/pfsense-logo-square.png",
          "debian":"https://imgur.com/a/Oe8z1Yb",
          "macos":"https://i.imgur.com/mxMJbg5.png",
          "vmware":"https://imgur.com/bXH4oFE.png"
          }
